### PR TITLE
Swift Version

### PR DESCRIPTION
**Pull request by sachinvas-halodoc**
@plivesey We have missed updating the swift_version, can you help us with merging this MR and create a new tag?

### CODE REVIEW

**Review by plivesey — COMMENTED** [review]
Do we need to update the spec version too? Also, by adding the swift version to the pod spec does that mean this is no longer compatible with swift 4?

**Comment by sachinvas-halodoc** [comment]
CocoaPods have moved to spec version and deprecated `.swift_version`, will delete the .swift_version file.

The source code doesn't support Swift 4 as we are using the latest APIs i.e `UIApplication.didReceiveMemoryWarningNotification` which is throwing an error below 4.2

**Review by plivesey — APPROVED** [review]

**Comment by plivesey** [comment]
I've gone ahead and created the 8.0.1 tag with this PR in it. Thanks for the update.

**Comment by sachinvas-halodoc** [comment]
@plivesey Thank you for accepting the MR, we have created the tag 8.0.1 however we missed publishing the podspec to CocoaPods. Please help.

**Comment by plivesey** [comment]
Updated the podspec to 8.0.1 and pushed to CocoaPods trunk. 👍

**Pull request merged**
